# choix de la version de docker compose
version: '3'
# Définition des services (conteneurs) de l'appli
services:
  python:
    image: sueyss/vote
    ports:
      - "8080:8080"
    networks:
      - batman
      - batman-back
    depends_on:
      - redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  node:
    image: sueyss/result
    ports:
      - "8888:8888"
    networks:
      - batman
      - batman-back
    depends_on:
      - postgres
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://postgres:5432"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  dotnet:
    image: sueyss/worker
    networks:
      - batman-back
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - batman-back
    volumes:
      - postgres-data:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  redis:
    image: "redis:latest"
    networks:
      - batman-back
    volumes:
      - redis-data:/data
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://python:8080"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 1
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  
  

# Définition du réseau "batman" pour le front-end et "batman-back" pour le back-end
networks:
  batman:
  batman-back:

# Définition des volumes pour le stockage persistant
volumes:
  postgres-data:
  redis-data: